import { StyleSheet } from "@react-pdf/renderer";

export const quotationPdfStyles = StyleSheet.create({
  page: {
    paddingTop: 34,
    paddingBottom: 34,
    paddingHorizontal: 30,
    fontSize: 10,
    fontFamily: "Helvetica",
    color: "#111111",
    lineHeight: 1.5,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 18,
  },
  logo: { width: 86 },
  companyInfo: { textAlign: "right", fontSize: 9, width: "66%" },
  companyName: {
    fontFamily: "Helvetica-Bold",
    fontSize: 10,
    textTransform: "uppercase",
  },
  divider: { borderBottom: "0.5pt solid #cccccc", marginVertical: 8 },
  label: {
    color: "#555555",
    fontFamily: "Helvetica-Bold",
    fontSize: 10,
    marginRight: 4,
    flexShrink: 0,
  },
  bold: {
    fontFamily: "Helvetica-Bold",
  },
  fieldRow: {
    flexDirection: "row",
    marginBottom: 6,
    alignItems: "flex-start",
    flexWrap: "wrap",
  },
  fieldValue: {
    flex: 1,
    fontSize: 10,
  },
  twoColumnFieldContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 12,
    gap: 12,
  },
  twoColumnField: {
    width: "48%",
    flexDirection: "row",
    alignItems: "flex-start",
    flexWrap: "wrap",
  },
  sectionTitle: {
    fontFamily: "Helvetica-Bold",
    fontSize: 10,
    textTransform: "uppercase",
    marginBottom: 8,
    marginTop: 12,
  },
  table: { border: "0.5pt solid #b9b9b9", marginBottom: 12 },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#f0f0f0",
    borderBottom: "0.5pt solid #b9b9b9",
  },
  tableRow: {
    flexDirection: "row",
    borderBottom: "0.5pt solid #b9b9b9",
    minHeight: 24,
    alignItems: "center",
  },
  tableCellBase: {
    padding: "6pt 6pt",
    fontSize: 9,
    display: "flex",
    alignItems: "center",
  },
  colDescription: { flex: 2.2 },
  colCurrency: { flex: 0.8 },
  colUom: { flex: 1 },
  colQuantity: { flex: 0.9 },
  colContainer: { flex: 1.2 },
  colAmount: { flex: 1.1 },
  colTotal: { flex: 1.2 },
  tableCellLast: {
    padding: "6pt 6pt",
    fontSize: 9,
    display: "flex",
    alignItems: "center",
    borderLeft: "0.5pt solid #b9b9b9",
  },
  tableCellRight: { textAlign: "right" },
  rowNote: {
    fontSize: 8,
    color: "#666666",
    paddingTop: 2,
    marginTop: 2,
  },
  totalRow: {
    flexDirection: "row",
    borderTop: "1pt solid #b9b9b9",
    backgroundColor: "#f9f9f9",
    fontFamily: "Helvetica-Bold",
    alignItems: "center",
    minHeight: 24,
  },
  sectionNote: {
    fontSize: 8,
    color: "#666666",
    marginTop: 4,
    paddingHorizontal: 6,
    paddingBottom: 6,
  },
  signatoryBlock: {
    flexDirection: "row",
    marginTop: 24,
    gap: 40,
  },
  signatoryCol: {
    flex: 1,
    alignItems: "center",
    textAlign: "center",
  },
  signature: {
    width: 80,
    height: 30,
    objectFit: "contain",
    marginVertical: 8,
  },
  footer: {
    textAlign: "center",
    color: "#888888",
    fontSize: 9,
    marginTop: 16,
  },
});
